// This code has been generated by the C2W code generator.
// Do not edit manually!

package TripleFederation;

import hla.rti.EventRetractionHandle;
import hla.rti.LogicalTime;
import hla.rti.ReceivedInteraction;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import c2w.hla.C2WInteractionRoot;
import c2w.hla.C2WLogger;
import c2w.hla.InteractionRoot;
import c2w.hla.SubscribedInteractionFilter;
import c2w.hla.SynchronizedFederate;


public class TripleSendBase extends SynchronizedFederate {

	private final static Logger log = LogManager.getLogger(TripleSendBase.class);
	
	private SubscribedInteractionFilter _subscribedInteractionFilter = new SubscribedInteractionFilter();
	
	// constructor
	public TripleSendBase( String federation_id, String federate_id ) throws Exception {
	
		setLookahead( 0.2 );
		createRTI();
		joinFederation( federation_id, federate_id );

		enableTimeConstrained();

		enableTimeRegulation( getLookahead() );
		enableAsynchronousDelivery();
        // interaction pubsub
        
        Int2.publish( getRTI() );
        Int3.publish( getRTI() );
        Int1.publish( getRTI() );
        		
		// object pubsub
                        }
        
       // constructor
	public TripleSendBase(  String[] federationInfo ) throws Exception {
		setLookahead( 0.2 );
		createRTI();
		joinFederation( federationInfo[ 0 ], federationInfo[ 1 ] );

		String loglevel = null;
		if(federationInfo.length == 3)
			C2WLogger.init( federationInfo[ 2 ] );
		else if(federationInfo.length > 3)
			C2WLogger.init( federationInfo[ 2 ], federationInfo[ 3 ] );		
		
		if(federationInfo.length == 5)
			loglevel = federationInfo[ 4 ];

		enableTimeConstrained();
		enableTimeRegulation( getLookahead() );
		enableAsynchronousDelivery();

        // interaction pubsub

        Int2.publish( getRTI() );
        Int3.publish( getRTI() );
        Int1.publish( getRTI() );
		// object pubsub
                		// enable pubsub log
		if(federationInfo.length  > 2) {
			
			Int2.enablePublishLog(
				"Int2",
				"TripleSend",
				"NORMAL",
				loglevel);
			Int3.enablePublishLog(
				"Int3",
				"TripleSend",
				"NORMAL",
				loglevel);
			Int1.enablePublishLog(
				"Int1",
				"TripleSend",
				"NORMAL",
				loglevel);
		}
		
	}
	
	public Int2 create_Int2() {
	   Int2 interaction = new Int2();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}
	public Int3 create_Int3() {
	   Int3 interaction = new Int3();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}
	public Int1 create_Int1() {
	   Int1 interaction = new Int1();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}

	@Override
	public void receiveInteraction(
	 int interactionClass, ReceivedInteraction theInteraction, byte[] userSuppliedTag
	) {
		InteractionRoot interactionRoot = InteractionRoot.create_interaction( interactionClass, theInteraction );
		if ( interactionRoot instanceof C2WInteractionRoot ) {
			
			C2WInteractionRoot c2wInteractionRoot = (C2WInteractionRoot)interactionRoot;

	        // Filter interaction if src/origin fed requirements (if any) are not met
	        if (  _subscribedInteractionFilter.filterC2WInteraction( getFederateId(), c2wInteractionRoot )  ) {
	        	return;
	        } 
		}
		
		super.receiveInteraction( interactionClass, theInteraction, userSuppliedTag );			
	}

	@Override
	public void receiveInteraction(
	 int interactionClass,
	 ReceivedInteraction theInteraction,
	 byte[] userSuppliedTag,
	 LogicalTime theTime,
	 EventRetractionHandle retractionHandle
	) {
		InteractionRoot interactionRoot = InteractionRoot.create_interaction( interactionClass, theInteraction, theTime );
		if ( interactionRoot instanceof C2WInteractionRoot ) {

			C2WInteractionRoot c2wInteractionRoot = (C2WInteractionRoot)interactionRoot;

	        // Filter interaction if src/origin fed requirements (if any) are not met
	        if (  _subscribedInteractionFilter.filterC2WInteraction( getFederateId(), c2wInteractionRoot )  ) {
	        	return;
	        } 
		}

		super.receiveInteraction( interactionClass, theInteraction, userSuppliedTag, theTime, retractionHandle );			
	}
}
